# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies for both client and server
      - name: Install Dependencies (Root)
        run: npm install

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      # Run linting (if you have a lint script in package.json)
      - name: Lint
        run: npm run lint

      # Build the client and server
      - name: Build Client and Server
        run: npm run build

      # Optionally, run tests if you have a test script
      #- name: Run Tests
      #  run: npm test
